#!/bin/bash

ldconfig

# Add to services
service mysql_server on
service findik on

# If mysql-server is installed and not running, start mysql-server.
[ -n "$(service list|grep mysql_server)" ] && \
	(service mysql_server start)

# Import MySQL schema
if (echo|mysql); then
	if [ -z "$(echo 'show databases'|mysql|grep -e '^findik$')" ]; then
		( mysqladmin create findik && \
		mysql findik < /usr/share/findik/sql/schema.sql ) || ( \
		echo "================================================="; \
		echo "|   A problem occured while importing schema.   |"; \
		echo "|   Please create a database and import         |"; \
		echo "|   /usr/share/findik/sql/schema.sql manually.  |"; \
		echo "================================================="; \
		echo; )
	else
		echo "================================================="
		echo "|   A database named 'findik' exists on MySQL.  |"
		echo "|   Please create a database and import         |"
		echo "|   /usr/share/findik/sql/schema.sql manually.  |"
		echo "================================================="
		echo
	fi
else
	echo "================================================="
	echo "|   Can not access MySQL.                       |"
	echo "|   Please create a database and import         |"
	echo "|   /usr/share/findik/sql/schema.sql manually.  |"
        echo "|   Also, edit MySQL credentials in             |"
	echo "|   /etc/findik/findik.cfg .                    |"
	echo "================================================="
	echo
fi

# Generating SSL keys.
if [ ! -f /etc/findik/ssl/public.pem -a ! -f /etc/findik/ssl/private.pem -a ! -f /etc/findik/ssl/dh.pem ]; then
	if (echo -e "ME\nRohan\nCalenardhon\nRohirrim\n\n*\nrohirrim@example.com\n"| \
		/usr/share/findik/scripts/generate-ssl-keys /etc/findik/ssl 512); then
		echo "================================================="
		echo "|   Created initial SSL keys and 512-byte DH    |"
		echo "|   parameters. If you want to recreate them,   |"
		echo "|   you can call                                |"
		echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
		echo "================================================="
		echo
	else
		echo "================================================="
		echo "|   A problem occured during key generation.    |"
		echo "|   Please recall and inspect output of         |"
		echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
		echo "|   command.                                    |"
		echo "================================================="
		echo
	fi
else
	echo "================================================="
	echo "|   Found SSL keys at /etc/findik/ssl/ and      |"
	echo "|   kept unchanged. If you want to recreate     |"
	echo "|   them, you can call                          |"
	echo "|   /usr/share/findik/scripts/generate-ssl-keys |"
	echo "================================================="
	echo
fi

service findik start

